package:
  name: docutils
  version: !!str 0.8.1

source:
  fn: docutils-0.8.1.tar.gz
  url: https://pypi.python.org/packages/source/d/docutils/docutils-0.8.1.tar.gz
  md5: 2ecf8ba3ece1be1ed666150a80c838c8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docutils = docutils:main
    #
    # Would create an entry point called docutils that calls docutils.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - docutils.transforms
    - docutils.parsers.rst
    - docutils.readers
    - docutils.math
    - docutils.languages
    - docutils.parsers.rst.languages
    - docutils.writers.pep_html
    - docutils.parsers
    - docutils.writers.xetex
    - docutils.writers.s5_html
    - docutils.writers.html4css1
    - docutils
    - docutils.writers.odf_odt
    - docutils.writers
    - docutils.writers.latex2e
    - docutils.parsers.rst.directives

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://docutils.sourceforge.net/
  license: BSD License or GNU General Public License (GPL) or Python Software Foundation License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
