{% set name = "httpie" %}
{% set version = "0.9.9" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f1202e6fa60367e2265284a53f35bfa5917119592c2ab08277efc7fffd744fcb" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - http = httpie.__main__:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - requests >=2.11.0
    - pygments >=2.1.3
  run:
    - python
    - requests >=2.11.0
    - pygments >=2.1.3

test:
  imports:
    - httpie
    - httpie.output
    - httpie.output.formatters
    - httpie.plugins
  commands:
    - http --help
  requires:
    - mock
    - pytest

about:
  home: http://httpie.org/
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: HTTPie - a CLI, cURL-like tool for humans.
  description: "HTTPie: a CLI, cURL-like tool for humans"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
