package:
  name: rudolf2
  version: 0.3

source:
  fn: rudolf2-0.3.tar.gz
  url: https://pypi.python.org/packages/source/r/rudolf2/rudolf2-0.3.tar.gz
  md5: 02d4d967f3a3707ecdf6f001e9aba6a3
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sqlobject = sqlobject:main
    #
    # Would create an entry point called sqlobject that calls sqlobject.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - nose

  run:
    - python

about:
  home: http://pypi.python.org/pypi/rudolf/
  license: ZPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
