package:
  name: haigha
  version: !!str 0.7.0

source:
  fn: haigha-0.7.0.tar.gz
  url: https://pypi.python.org/packages/source/h/haigha/haigha-0.7.0.tar.gz
  md5: b4042c0f0566940ab454b6b942b37009
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - haigha = haigha:main
    #
    # Would create an entry point called haigha that calls haigha.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - haigha.classes
    - haigha.frames
    - haigha
    - haigha.transports
    - haigha.connections

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/agoragames/haigha
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
