package:
  name: pyes
  version: 0.90.1

source:
  fn: pyes-0.90.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyes/pyes-0.90.1.tar.gz
  md5: b54f76837b14fc76ba7b125badb8d5fc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1
# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sqlobject = sqlobject:main
    #
    # Would create an entry point called sqlobject that calls sqlobject.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - urllib3
    - six

  run:
    - python
    - urllib3

about:
  home: http://github.com/aparo/pyes/
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
