package:
  name: docker-py
  version: !!str 0.2.3

source:
  fn: docker-py-0.2.3.tar.gz
  url: https://pypi.python.org/packages/source/d/docker-py/docker-py-0.2.3.tar.gz
  md5: b6f8b5aec30d1b2eb8b47d1c0e087cee
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docker-py = docker-py:main
    #
    # Would create an entry point called docker-py that calls docker-py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - mock
    - requests
    - six
    - websocket-client

  run:
    - python
    - mock
    - requests
    - six
    - websocket-client

test:
  # Python imports
  imports:
    - docker

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: UNKNOWN
  license: ache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
