package:
  name: elasticsearch
  version: !!str 0.4.5

source:
  fn: elasticsearch-0.4.5.tar.gz
  url: https://pypi.python.org/packages/source/e/elasticsearch/elasticsearch-0.4.5.tar.gz
  md5: 61c288be480fadfb1a558c522dd16990
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - elasticsearch = elasticsearch:main
    #
    # Would create an entry point called elasticsearch that calls elasticsearch.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - urllib3

  run:
    - python
    - urllib3

test:
  # Python imports
  imports:
    - elasticsearch.client
    - elasticsearch
    - elasticsearch.connection
    - elasticsearch.connection.esthrift

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/elasticsearch/elasticsearch-py
  license: ache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
