package:
  name: oauthlib
  version: 0.6.1

source:
  fn: oauthlib-0.6.1.tar.gz
  url: https://pypi.python.org/packages/source/o/oauthlib/oauthlib-0.6.1.tar.gz
  md5: 18f8524c85606380c1ef8a7ff50d69cc
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sqlobject = sqlobject:main
    #
    # Would create an entry point called sqlobject that calls sqlobject.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/idan/oauthlib
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
