package:
  name: fig
  version: !!str 0.5.2

source:
  fn: fig-0.5.2.tar.gz
  url: https://pypi.python.org/packages/source/f/fig/fig-0.5.2.tar.gz
  md5: 3dd032da472e35199d55c8620d3eac26
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - fig = fig:main
    #
    # Would create an entry point called fig that calls fig.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docopt ==0.6.1
    - pyyaml ==3.10
    - requests ==2.2.1
    - texttable ==0.8.1
    - websocket-client ==0.11.0
    - dockerpty ==0.2.3

  run:
    - python
    - docopt ==0.6.1
    - pyyaml ==3.10
    - requests ==2.2.1
    - texttable ==0.8.1
    - websocket-client ==0.11.0
    - dockerpty ==0.2.3

test:
  # Python imports
  imports:
    - fig
    - fig.cli
    - fig.packages
    - fig.packages.docker
    - fig.packages.docker.auth
    - fig.packages.docker.unixconn
    - fig.packages.docker.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.fig.sh/
  license: Apache License 2.0
  summary: 'Punctual, lightweight development environments using Docker'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
