package:
  name: flask
  version: !!str 0.8

source:
  fn: Flask-0.8.tar.gz
  url: https://pypi.python.org/packages/source/F/Flask/Flask-0.8.tar.gz
  md5: a5169306cfe49b3b369086f2a63816ab
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask = flask:main
    #
    # Would create an entry point called flask that calls flask.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - werkzeug
    - jinja2

  run:
    - python
    - werkzeug
    - jinja2

test:
  # Python imports
  imports:
    - flask
    - flask.ext
    - flask.testsuite

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mitsuhiko/flask/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
