package:
  name: lxml
  version: !!str 2.3.2

source:
  fn: lxml-2.3.2.tar.gz
  url: https://pypi.python.org/packages/source/l/lxml/lxml-2.3.2.tar.gz
  md5: 50ed3706da4665c40600fd6e2a7d1159
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 2

requirements:
  build:
    - libxml2
    - libxslt
    - python

  run:
    - libxml2
    - libxslt
    - python

test:
  # Python imports
  imports:
    - lxml.isoschematron
    - lxml
    - lxml.html

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://lxml.de/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
