package:
  name: finite
  version: !!str 0.1.0

source:
  fn: finite-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/f/finite/finite-0.1.0.tar.gz
  md5: 680f8c1b30cd591a92dc2acef61c455f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - finite = finite:main
    #
    # Would create an entry point called finite that calls finite.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - finite

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/barnybug/finite/
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
